title: <p align="center"> Vishnu CV </p>
logo: /assets/img/Vishnu.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vishnucvinod">LinkedIn</a> |
  <a href="https://github.com/vishnucvinod">GitHub</a>
  
  <br>   
  I'm working as DevOps Engineer at Zero Pixels Technologies.
  <br>
  </p>



theme: jekyll-theme-minimal
